[project.scripts]
pybundle = "pybundle.cli:main"

[project]
name = "pybundle"
version = "0.3.2"

[tool.setuptools.packages.find]
include = ["pybundle*"]
exclude = ["artifacts*", ".pybundle*"]

[tool.setuptools]
include-package-data = false
